// Service landing pages — written for search in Iraq first (Arabic, incl. Iraqi everyday terms),
// then Iran (Persian) and international clients (English).
import type { Locale } from './i18n'

type Block = { title: string; h1: string; description: string; intro: string; points: string[]; faq: [string, string][] }
export type ServicePage = { slug: string; icon: string } & Record<Locale, Block>

export const SERVICE_PAGES: ServicePage[] = [
  {
    slug: 'mep-design', icon: '⚙️',
    ar: {
      title: 'تصميم التأسيسات الميكانيكية والكهربائية MEP في العراق | فن آرا',
      h1: 'تصميم وتنفيذ التأسيسات الميكانيكية والكهربائية (MEP) في العراق',
      description: 'مكتب هندسي لتصميم مخططات التأسيسات MEP: الماء والمجاري، الكهرباء، التكييف، غرف المضخات والمراجل والمسابح — للمشاريع السكنية والتجارية والصناعية في العراق، مع إشراف على التنفيذ.',
      intro: 'نصمم مخططات التأسيسات الميكانيكية والكهربائية لكل أنواع المباني، ونتابعها في الموقع حتى التسليم. خبرة تزيد على 15 عامًا في مشاريع سكنية كبيرة، منها تسليم تأسيسات 800 وحدة سكنية خلال 9 أشهر ضمن مشروع من 3,500 وحدة في العراق.',
      points: ['مخططات تأسيس الماء والمجاري (الصحيات) وحساب الأقطار والميول', 'مخططات الكهرباء: الإنارة، المآخذ، اللوحات، حساب الأحمال والكابلات', 'التكييف والتهوية: حساب الأحمال الحرارية واختيار المنظومة', 'غرف المضخات والمراجل وخزانات الماء', 'تنسيق التأسيسات مع المخطط المعماري والإنشائي لتجنب التعارضات', 'جداول الكميات (BOQ) والمواصفات والإشراف على التنفيذ'],
      faq: [['هل تصممون مخططات لمشروع واحد (بيت أو فيلا)؟', 'نعم، نصمم لبيت واحد أو فيلا أو عمارة أو مجمع سكني كامل. أرسل المخطط المعماري واحصل على عرض سعر.'], ['هل تشرفون على التنفيذ في الموقع؟', 'نعم، نتابع التنفيذ ونراجع أعمال التأسيس قبل الصب والإغلاق لضمان مطابقتها للمخططات.'], ['كم يستغرق تصميم مخططات التأسيسات؟', 'يعتمد على حجم المشروع؛ نرسل الجدول الزمني مع عرض السعر بعد مراجعة المخطط.']],
    },
    fa: {
      title: 'طراحی تأسیسات مکانیکی و برقی (MEP) | دفتر مهندسی فن آرا',
      h1: 'طراحی و اجرای تأسیسات مکانیکی و برقی ساختمان (MEP)',
      description: 'دفتر مهندسی فن آرا: طراحی نقشه‌های تأسیسات مکانیکی و برقی، آب و فاضلاب، تهویه مطبوع، موتورخانه و استخر برای پروژه‌های مسکونی، تجاری و صنعتی در ایران و عراق، همراه با نظارت اجرا.',
      intro: 'نقشه‌های تأسیسات مکانیکی و برقی هر نوع ساختمان را طراحی می‌کنیم و تا تحویل در کارگاه همراه پروژه هستیم؛ با بیش از ۱۵ سال تجربه، از جمله تحویل تأسیسات ۸۰۰ واحد مسکونی در ۹ ماه در پروژه‌ای ۳٬۵۰۰ واحدی در عراق.',
      points: ['نقشه‌های آب و فاضلاب با محاسبه‌ی قطر و شیب لوله‌ها', 'نقشه‌های برق: روشنایی، پریز، تابلوها، محاسبه‌ی بار و کابل', 'تهویه مطبوع: محاسبه‌ی بار حرارتی و انتخاب سیستم', 'موتورخانه، پمپ‌خانه و مخازن آب', 'هماهنگی تأسیسات با نقشه‌های معماری و سازه برای جلوگیری از تداخل', 'متره و برآورد، مشخصات فنی و نظارت اجرا'],
      faq: [['برای یک ساختمان کوچک یا ویلا هم طراحی می‌کنید؟', 'بله؛ از یک ویلا تا مجتمع مسکونی کامل. نقشه‌ی معماری را بفرستید و پیش‌فاکتور بگیرید.'], ['نظارت بر اجرا هم انجام می‌دهید؟', 'بله؛ پیش از بتن‌ریزی و بسته شدن کار، اجرای تأسیسات را با نقشه‌ها کنترل می‌کنیم.'], ['طراحی چقدر زمان می‌برد؟', 'به اندازه‌ی پروژه بستگی دارد؛ زمان‌بندی همراه پیش‌فاکتور اعلام می‌شود.']],
    },
    en: {
      title: 'MEP Design & Installation in Iraq | Fanara Engineering',
      h1: 'Mechanical, Electrical & Plumbing (MEP) Design and Installation in Iraq',
      description: 'Fanara Engineering designs MEP drawings — water and drainage, electrical, HVAC, pump and boiler rooms, swimming pools — for residential, commercial and industrial projects in Iraq, with site supervision.',
      intro: 'We design mechanical and electrical services for every building type and follow them on site through handover — 15+ years of experience, including MEP for 800 housing units delivered in 9 months on a 3,500-unit project in Iraq.',
      points: ['Water supply and drainage drawings with pipe sizing and slopes', 'Electrical: lighting, power, panels, load and cable calculations', 'HVAC: heat-load calculation and system selection', 'Pump rooms, boiler rooms and water tanks', 'MEP coordination with architectural and structural drawings (clash-free)', 'BOQ, specifications and site supervision'],
      faq: [['Do you design for a single house or villa?', 'Yes — from a single villa to a full residential compound. Send the architectural plan for a quote.'], ['Do you supervise installation on site?', 'Yes. We check installations against the drawings before concrete pours and close-up.'], ['How long does MEP design take?', 'It depends on project size; the schedule comes with the quote.']],
    },
  },
  {
    slug: 'plumbing', icon: '🚰',
    ar: {
      title: 'تأسيس ماء ومجاري وتأسيسات صحية في العراق | فن آرا',
      h1: 'التأسيسات الصحية: تأسيس الماء والمجاري في العراق',
      description: 'تصميم وتنفيذ التأسيسات الصحية (الصحيات): تأسيس الماء الحار والبارد، شبكات المجاري وتصريف الأمطار، خزانات الماء ومضخات الضغط — للبيوت والعمارات والمجمعات السكنية في العراق.',
      intro: 'التأسيس الصحي الجيد يمنع النضوح والانسداد ومشاكل الضغط لسنين. نصمم شبكة الماء والمجاري بالحسابات الصحيحة وننفذها بمواد مناسبة (PPR، UPVC، HDPE) مع اختبار الضغط قبل الإغلاق.',
      points: ['تأسيس الماء الحار والبارد بأنابيب PPR ومنفولدات التوزيع', 'شبكات المجاري الداخلية والخارجية والمنهولات بالميول الصحيحة', 'تصريف مياه الأمطار والسطوح', 'خزانات الماء العلوية والأرضية ومضخات رفع الضغط', 'تأسيس الحمامات والمطابخ والسيفونات والمراحيض المعلقة', 'اختبار الضغط والتسرب قبل التغليف والصب'],
      faq: [['ما الفرق بين التأسيس الجيد والرديء؟', 'التأسيس الجيد يعتمد على حساب الأقطار والميول واختبار الضغط، فلا يظهر نضوح أو ضعف ضغط بعد السكن.'], ['هل تنفذون شبكة مجاري لمجمع سكني كامل؟', 'نعم، نفذنا شبكات مجاري خارجية بمنهولات لمشاريع سكنية كبيرة في العراق.']],
    },
    fa: {
      title: 'طراحی و اجرای تأسیسات آب و فاضلاب ساختمان | فن آرا',
      h1: 'تأسیسات بهداشتی: لوله‌کشی آب و فاضلاب ساختمان',
      description: 'طراحی و اجرای لوله‌کشی آب سرد و گرم، شبکه‌ی فاضلاب و آب باران، مخازن و پمپ‌های افزایش فشار برای ساختمان‌ها و مجتمع‌های مسکونی در ایران و عراق.',
      intro: 'لوله‌کشی اصولی سال‌ها جلوی نشتی، گرفتگی و افت فشار را می‌گیرد. شبکه‌ی آب و فاضلاب را با محاسبه‌ی درست طراحی و با مصالح مناسب (PPR، UPVC، HDPE) اجرا می‌کنیم و پیش از پوشاندن، تست فشار می‌گیریم.',
      points: ['لوله‌کشی آب سرد و گرم با PPR و منیفولد', 'فاضلاب داخلی و خارجی و منهول با شیب صحیح', 'دفع آب باران و بام', 'مخازن آب و پمپ‌های افزایش فشار', 'تأسیسات حمام، آشپزخانه و توالت وال‌هنگ', 'تست فشار و نشتی پیش از پوشش و بتن‌ریزی'],
      faq: [['تفاوت لوله‌کشی اصولی و غیراصولی چیست؟', 'محاسبه‌ی قطر و شیب و تست فشار؛ نتیجه‌اش نبودِ نشتی و افت فشار بعد از بهره‌برداری است.'], ['شبکه‌ی فاضلاب مجتمع را هم اجرا می‌کنید؟', 'بله؛ شبکه‌های خارجی فاضلاب با منهول را در پروژه‌های بزرگ مسکونی اجرا کرده‌ایم.']],
    },
    en: {
      title: 'Plumbing & Drainage Design and Installation in Iraq | Fanara',
      h1: 'Plumbing: Water Supply and Drainage Installation in Iraq',
      description: 'Design and installation of hot and cold water, drainage and stormwater networks, water tanks and booster pumps for houses, apartment buildings and residential compounds in Iraq.',
      intro: 'Good plumbing prevents leaks, blockages and pressure problems for years. We size the water and drainage network properly, install it with suitable materials (PPR, UPVC, HDPE) and pressure-test before close-up.',
      points: ['Hot and cold water in PPR with distribution manifolds', 'Internal and external drainage with manholes and correct falls', 'Roof and stormwater drainage', 'Roof and ground tanks, booster pumps', 'Bathrooms, kitchens, wall-hung WC frames', 'Pressure and leak testing before close-up'],
      faq: [['What makes plumbing installation good?', 'Correct pipe sizing and falls plus pressure testing — no leaks or low pressure after handover.'], ['Do you install compound-wide drainage networks?', 'Yes, we have installed external sewer networks with manholes on large housing projects in Iraq.']],
    },
  },
  {
    slug: 'electrical', icon: '⚡',
    ar: {
      title: 'تأسيس كهربائيات وتصميم المخططات الكهربائية في العراق | فن آرا',
      h1: 'التأسيسات الكهربائية: تصميم وتأسيس الكهرباء في العراق',
      description: 'تصميم المخططات الكهربائية وتأسيس الكهرباء: الإنارة والمآخذ، اللوحات الرئيسية والفرعية، حساب الأحمال، المولدات وخطوط التغذية — للبيوت والعمارات والمشاريع في العراق.',
      intro: 'نصمم المنظومة الكهربائية من حساب الأحمال إلى اللوحات وتوزيع الدوائر، ونراعي واقع الكهرباء في العراق (الوطنية والمولدة) بمفاتيح التحويل والتوزيع المناسب.',
      points: ['مخططات الإنارة والمآخذ وتوزيع الدوائر', 'تصميم وتجميع اللوحات الرئيسية والفرعية', 'حساب الأحمال ومقاطع الكابلات والقواطع', 'ربط المولدة ومفاتيح التحويل (ATS)', 'التأريض والحماية', 'الإشراف على التأسيس والفحص قبل التشغيل'],
      faq: [['هل تراعون الوطنية والمولدة في التصميم؟', 'نعم، نصمم التوزيع ومفاتيح التحويل بحيث تعمل الأحمال المهمة على المولدة بأمان.'], ['هل تصممون اللوحات الكهربائية؟', 'نعم، نصمم اللوحة من المخطط إلى التجميع والتنفيذ.']],
    },
    fa: {
      title: 'طراحی و اجرای تأسیسات برقی ساختمان | دفتر مهندسی فن آرا',
      h1: 'تأسیسات برقی: طراحی نقشه‌ی برق و اجرای سیم‌کشی',
      description: 'طراحی نقشه‌های برق ساختمان: روشنایی و پریز، تابلوهای اصلی و فرعی، محاسبه‌ی بار، ژنراتور و کلید انتقال، ارت و حفاظت — برای پروژه‌های ایران و عراق.',
      intro: 'سیستم برق را از محاسبه‌ی بار تا تابلو و تقسیم مدارها طراحی می‌کنیم؛ همراه با اتصال ژنراتور و کلید انتقال اتوماتیک برای شبکه‌های ناپایدار.',
      points: ['نقشه‌ی روشنایی و پریز و تقسیم مدارها', 'طراحی و مونتاژ تابلوهای اصلی و فرعی', 'محاسبه‌ی بار، سطح مقطع کابل و فیوزها', 'اتصال ژنراتور و کلید انتقال (ATS)', 'ارتینگ و حفاظت', 'نظارت بر اجرا و تست پیش از بهره‌برداری'],
      faq: [['تابلو برق را هم طراحی و اجرا می‌کنید؟', 'بله؛ از نقشه‌ی تک‌خطی تا مونتاژ و نصب.'], ['برای برق ناپایدار چه راهکاری دارید؟', 'ژنراتور با کلید انتقال اتوماتیک و تفکیک بارهای ضروری.']],
    },
    en: {
      title: 'Electrical Design & Installation in Iraq | Fanara Engineering',
      h1: 'Electrical Installations: Design and Wiring in Iraq',
      description: 'Electrical design and installation: lighting and power, main and sub-distribution panels, load calculations, generators and transfer switches, earthing — for homes, buildings and projects in Iraq.',
      intro: 'We design the electrical system from load calculation to panels and circuits, designed for the reality of grid plus generator supply in Iraq, with proper changeover and distribution.',
      points: ['Lighting and power layouts, circuiting', 'Main and sub-panel design and assembly', 'Load, cable and breaker sizing', 'Generator connection and ATS changeover', 'Earthing and protection', 'Site supervision and pre-energisation testing'],
      faq: [['Do you design for grid + generator supply?', 'Yes — changeover and distribution so essential loads run safely on the generator.'], ['Do you design electrical panels?', 'Yes, from single-line diagram to assembly and installation.']],
    },
  },
  {
    slug: 'hvac', icon: '❄️',
    ar: {
      title: 'تصميم التكييف والتهوية HVAC والتكييف المركزي في العراق | فن آرا',
      h1: 'التكييف والتهوية: تصميم منظومات HVAC في العراق',
      description: 'حساب الأحمال الحرارية وتصميم التكييف المركزي والسبلت والدكت والفانكويل والتهوية للمباني السكنية والتجارية في مناخ العراق الحار.',
      intro: 'في صيف العراق، اختيار المنظومة الصحيحة يوفر الكهرباء والكلفة. نحسب الأحمال الحرارية لكل فضاء ونختار المنظومة المناسبة: سبلت، دكت سبلت، فانكويل وتشلر، أو VRF، مع مجاري الهواء والتهوية.',
      points: ['حساب الأحمال الحرارية لكل غرفة', 'تصميم مجاري الهواء (الدكت) والفتحات', 'منظومات الفانكويل والتشلر و VRF', 'تهوية الحمامات والمطابخ والسراديب', 'اختيار الأجهزة بكفاءة طاقة مناسبة', 'تنسيق المسارات مع الكهرباء والإنشائي'],
      faq: [['أيهما أفضل: سبلت أم تكييف مركزي؟', 'يعتمد على المساحة وعدد الطوابق والاستخدام؛ بعد حساب الأحمال نقترح الخيار الأوفر.'], ['هل تصممون تهوية السراديب والمطابخ؟', 'نعم، ضمن تصميم التهوية الكامل للمبنى.']],
    },
    fa: {
      title: 'طراحی تهویه مطبوع و تأسیسات HVAC | دفتر مهندسی فن آرا',
      h1: 'تهویه مطبوع: طراحی سیستم‌های سرمایش، گرمایش و تهویه',
      description: 'محاسبه‌ی بار حرارتی و طراحی سیستم‌های اسپلیت، داکت‌اسپلیت، فن‌کویل و چیلر، VRF و تهویه برای ساختمان‌های مسکونی و تجاری.',
      intro: 'انتخاب درست سیستم تهویه، مصرف برق و هزینه را کم می‌کند. بار حرارتی هر فضا را محاسبه و سیستم مناسب را همراه کانال‌کشی و تهویه طراحی می‌کنیم.',
      points: ['محاسبه‌ی بار حرارتی هر فضا', 'طراحی کانال‌کشی و دریچه‌ها', 'سیستم‌های فن‌کویل و چیلر و VRF', 'تهویه‌ی سرویس‌ها، آشپزخانه و زیرزمین', 'انتخاب تجهیزات با راندمان مناسب', 'هماهنگی مسیرها با برق و سازه'],
      faq: [['اسپلیت بهتر است یا سیستم مرکزی؟', 'به متراژ، تعداد طبقات و کاربری بستگی دارد؛ پس از محاسبه‌ی بار، به‌صرفه‌ترین گزینه را پیشنهاد می‌کنیم.']],
    },
    en: {
      title: 'HVAC & Central Air-Conditioning Design in Iraq | Fanara',
      h1: 'HVAC: Air-Conditioning and Ventilation Design in Iraq',
      description: 'Heat-load calculation and design of split, ducted, fan-coil/chiller and VRF systems plus ventilation for residential and commercial buildings in Iraq’s hot climate.',
      intro: 'In an Iraqi summer the right system saves power and money. We calculate the heat load of every space and select the right system — split, ducted split, fan-coil and chiller, or VRF — with ductwork and ventilation.',
      points: ['Room-by-room heat-load calculation', 'Ductwork and diffuser design', 'Fan-coil, chiller and VRF systems', 'Ventilation for bathrooms, kitchens and basements', 'Energy-efficient equipment selection', 'Route coordination with electrical and structure'],
      faq: [['Split units or central system?', 'It depends on area, floors and use; after the load calculation we recommend the most economical option.']],
    },
  },
  {
    slug: 'plant-room', icon: '🔥',
    ar: {
      title: 'تصميم غرف المراجل والمضخات (البويلرات) في العراق | فن آرا',
      h1: 'غرف المراجل والمضخات: تسخين الماء والتدفئة ورفع الضغط',
      description: 'تصميم وتنفيذ غرف المكائن: المراجل (البويلرات)، سخانات الماء المركزية، مضخات الدوران ورفع الضغط، خزانات التمدد — للمجمعات السكنية والفنادق والمستشفيات في العراق.',
      intro: 'غرفة المكائن قلب المبنى. نصمم المرجل وخزانات الماء الحار والمضخات والصمامات والتحكم بحيث يكون التشغيل آمنًا والصيانة سهلة، وقد نفذنا غرف مراجل لمشاريع سكنية وتجارية.',
      points: ['اختيار المراجل والحراقات وسخانات الماء المركزية', 'مضخات الدوران ورفع الضغط ومجموعات الضخ', 'خزانات التمدد والصمامات والحماية', 'المخطط الهيدروليكي (Schematic) لغرفة المكائن', 'تنسيق الأبعاد والتهوية والمدخنة', 'التشغيل التجريبي والضبط'],
      faq: [['هل تصممون غرفة مراجل لمجمع سكني؟', 'نعم، من الحسابات والمخطط الهيدروليكي إلى التنفيذ والتشغيل.'], ['ما الذي يحدد حجم المرجل؟', 'أحمال التدفئة والماء الحار وعدد الوحدات والاستخدام المتزامن؛ نحسبها قبل الاختيار.']],
    },
    fa: {
      title: 'طراحی و اجرای موتورخانه و پمپ‌خانه | دفتر مهندسی فن آرا',
      h1: 'موتورخانه و پمپ‌خانه: آب گرم مصرفی، گرمایش و افزایش فشار',
      description: 'طراحی و اجرای موتورخانه: دیگ و مشعل، منابع آب گرم، پمپ‌های سیرکولاسیون و بوستر، منبع انبساط و شماتیک موتورخانه برای مجتمع‌ها، هتل‌ها و ساختمان‌های تجاری.',
      intro: 'موتورخانه قلب ساختمان است. دیگ، منابع آب گرم، پمپ‌ها، شیرآلات و کنترل را طوری طراحی می‌کنیم که بهره‌برداری ایمن و نگهداری ساده باشد.',
      points: ['انتخاب دیگ، مشعل و منبع آب گرم', 'پمپ‌های سیرکولاسیون و بوستر پمپ', 'منبع انبساط، شیرآلات و حفاظت', 'نقشه‌ی شماتیک موتورخانه', 'هماهنگی ابعاد، تهویه و دودکش', 'راه‌اندازی و تنظیم'],
      faq: [['ظرفیت دیگ چطور تعیین می‌شود؟', 'از بار گرمایش و آب گرم مصرفی، تعداد واحدها و ضریب هم‌زمانی؛ پیش از انتخاب محاسبه می‌کنیم.']],
    },
    en: {
      title: 'Boiler Room & Pump Room Design in Iraq | Fanara Engineering',
      h1: 'Plant Rooms: Boilers, Hot Water, Heating and Booster Pumps',
      description: 'Design and installation of plant rooms — boilers and burners, central water heaters, circulation and booster pumps, expansion vessels and plant-room schematics — for compounds, hotels and hospitals in Iraq.',
      intro: 'The plant room is the heart of a building. We design boilers, hot-water storage, pumps, valves and controls for safe operation and easy maintenance.',
      points: ['Boiler, burner and calorifier selection', 'Circulation and booster pump sets', 'Expansion vessels, valves and protection', 'Plant-room hydraulic schematic', 'Layout, ventilation and flue coordination', 'Commissioning and balancing'],
      faq: [['How is boiler capacity sized?', 'From heating and hot-water loads, number of units and diversity; we calculate before selecting equipment.']],
    },
  },
  {
    slug: 'swimming-pools', icon: '🏊',
    ar: {
      title: 'تصميم وتأسيس المسابح: الفلترة والتسخين والدوران في العراق | فن آرا',
      h1: 'تأسيسات المسابح: الفلترة والتدوير والتسخين',
      description: 'تصميم وتنفيذ تأسيسات المسابح (حمامات السباحة) للبيوت والفلل والفنادق في العراق: غرفة الفلاتر، مضخات التدوير، التسخين، القطع المدفونة والإنارة تحت الماء.',
      intro: 'المسبح الناجح يبدأ من تأسيس صحيح قبل الصب. نحسب حجم الماء ومعدل التدوير، ونصمم غرفة الفلاتر والمضخات والتسخين والقطع المدفونة (السكيمر، المداخل، التصريف) بحيث يبقى الماء صافيًا والتشغيل اقتصاديًا.',
      points: ['حساب معدل التدوير واختيار الفلاتر الرملية والمضخات', 'غرفة مكائن المسبح والصمامات', 'القطع المدفونة: سكيمر، مداخل، تصريف أرضي', 'تسخين ماء المسبح ومبادلات الحرارة', 'الإنارة تحت الماء والتأريض الآمن', 'معالجة الماء والكلورة'],
      faq: [['هل تصممون مسبحًا لبيت أو فيلا؟', 'نعم، للمسابح الخاصة والفندقية؛ أرسل مخطط الموقع والأبعاد.'], ['متى يجب تنفيذ التأسيس؟', 'القطع المدفونة والأنابيب يجب أن تُنفذ قبل صب جسم المسبح.']],
    },
    fa: {
      title: 'طراحی و اجرای تأسیسات استخر: تصفیه، گردش آب و گرمایش | فن آرا',
      h1: 'تأسیسات استخر: فیلتراسیون، سیرکولاسیون و گرمایش آب',
      description: 'طراحی و اجرای تأسیسات استخر برای ویلا، هتل و مجموعه‌های ورزشی: موتورخانه‌ی استخر، فیلتر شنی و پمپ، گرمایش آب، قطعات مدفون و روشنایی زیر آب.',
      intro: 'استخر خوب از تأسیسات درستِ پیش از بتن‌ریزی شروع می‌شود. حجم آب و نرخ گردش را محاسبه و موتورخانه، پمپ، فیلتر، گرمایش و قطعات مدفون را طراحی می‌کنیم.',
      points: ['محاسبه‌ی نرخ گردش و انتخاب فیلتر شنی و پمپ', 'موتورخانه‌ی استخر و شیرآلات', 'قطعات مدفون: اسکیمر، نازل، کف‌شوی', 'گرمایش آب استخر و مبدل حرارتی', 'روشنایی زیر آب و ارت ایمن', 'تصفیه و کلرزنی'],
      faq: [['تأسیسات استخر باید چه زمانی اجرا شود؟', 'قطعات مدفون و لوله‌ها پیش از بتن‌ریزی بدنه‌ی استخر.']],
    },
    en: {
      title: 'Swimming Pool MEP: Filtration, Circulation & Heating in Iraq | Fanara',
      h1: 'Swimming Pool Installations: Filtration, Circulation and Heating',
      description: 'Design and installation of swimming-pool services for homes, villas and hotels in Iraq: filter room, circulation pumps, heating, embedded fittings and underwater lighting.',
      intro: 'A good pool starts with correct services before the concrete pour. We calculate water volume and turnover, then design the filter room, pumps, heating and embedded fittings.',
      points: ['Turnover rate, sand filters and pump selection', 'Pool plant room and valves', 'Embedded fittings: skimmers, inlets, main drains', 'Pool water heating and heat exchangers', 'Underwater lighting with safe earthing', 'Water treatment and chlorination'],
      faq: [['When must pool services be installed?', 'Embedded fittings and pipes go in before the pool shell is poured.']],
    },
  },
  {
    slug: 'maintenance', icon: '🛠️',
    ar: {
      title: 'صيانة الصحيات والكهرباء والمراجل والتكييف في العراق | فن آرا',
      h1: 'صيانة التأسيسات: الصحيات والكهرباء والميكانيك',
      description: 'صيانة دورية وطارئة للتأسيسات في العراق: صيانة الصحيات والنضوح، صيانة الكهرباء واللوحات، صيانة المراجل والمضخات والتكييف والمسابح — للبيوت والعمارات والفنادق والمجمعات.',
      intro: 'الصيانة الدورية أرخص بكثير من التصليح بعد العطل. نفحص التأسيسات ونحدد أسباب المشاكل (النضوح، ضعف الضغط، انقطاع الكهرباء، ضعف التبريد) ونصلحها من الأساس، مع عقود صيانة سنوية للمباني والفنادق والمجمعات.',
      points: ['صيانة الصحيات: كشف النضوح والتسربات وانسداد المجاري', 'صيانة الكهرباء: فحص اللوحات والقواطع والتأريض والأحمال', 'صيانة المراجل وسخانات الماء والمضخات', 'صيانة منظومات التكييف والتهوية', 'صيانة مكائن المسابح والفلاتر', 'عقود صيانة دورية مع تقارير فحص'],
      faq: [['هل تقدمون عقود صيانة سنوية؟', 'نعم، للعمارات والفنادق والمجمعات السكنية مع زيارات دورية وتقرير بعد كل زيارة.'], ['هل تحلون مشكلة النضوح من الأساس؟', 'نعم، نحدد مصدر التسرب بالفحص ونصلح الخلل في التأسيس بدل الحلول المؤقتة.']],
    },
    fa: {
      title: 'نگهداری و تعمیر تأسیسات ساختمان | دفتر مهندسی فن آرا',
      h1: 'نگهداری تأسیسات: آب و فاضلاب، برق و مکانیک',
      description: 'نگهداری دوره‌ای و تعمیرات تأسیسات: نشتی‌یابی و رفع گرفتگی، سرویس تابلو برق، دیگ و پمپ، سیستم تهویه و استخر، همراه با قرارداد نگهداری سالانه.',
      intro: 'نگهداری دوره‌ای بسیار ارزان‌تر از تعمیر پس از خرابی است. علت مشکل را پیدا و از ریشه برطرف می‌کنیم؛ با قرارداد نگهداری سالانه برای ساختمان‌ها، هتل‌ها و مجتمع‌ها.',
      points: ['نشتی‌یابی و رفع گرفتگی فاضلاب', 'سرویس تابلوها، کلیدها و ارت', 'سرویس دیگ، آبگرمکن و پمپ‌ها', 'سرویس سیستم‌های تهویه', 'سرویس موتورخانه و فیلترهای استخر', 'قرارداد نگهداری با گزارش بازدید'],
      faq: [['قرارداد نگهداری سالانه دارید؟', 'بله؛ با بازدیدهای دوره‌ای و گزارش پس از هر بازدید.']],
    },
    en: {
      title: 'MEP Maintenance: Plumbing, Electrical, Boilers & HVAC in Iraq | Fanara',
      h1: 'Building Services Maintenance: Plumbing, Electrical and Mechanical',
      description: 'Planned and emergency maintenance of building services in Iraq: leak detection, drainage, electrical panels, boilers and pumps, HVAC and pool plant — with annual maintenance contracts.',
      intro: 'Planned maintenance costs far less than repairs after a breakdown. We find the root cause of leaks, low pressure, power faults or weak cooling and fix it properly — with annual contracts for buildings, hotels and compounds.',
      points: ['Leak detection and drain blockages', 'Electrical panels, breakers, earthing and loads', 'Boilers, water heaters and pumps', 'HVAC system servicing', 'Pool plant and filters', 'Maintenance contracts with inspection reports'],
      faq: [['Do you offer annual maintenance contracts?', 'Yes — periodic visits with a report after each visit.']],
    },
  },
  {
    slug: 'engineering-design', icon: '📐',
    ar: {
      title: 'تصميم مخططات هندسية: معماري وإنشائي وتأسيسات | مكتب فن آرا الهندسي',
      h1: 'التصميم الهندسي: المخططات المعمارية والإنشائية والتأسيسات',
      description: 'مكتب هندسي متعدد الاختصاصات لتصميم المخططات المعمارية والإنشائية والميكانيكية والكهربائية للبيوت والعمارات والمشاريع التجارية في العراق، مع جداول الكميات.',
      intro: 'فريق فن آرا يضم مهندسين من كل الاختصاصات، فتحصل على مخططات متناسقة من مكان واحد: المعماري والإنشائي والتأسيسات، مع تنسيق يمنع التعارض في الموقع.',
      points: ['المخططات المعمارية (المساقط والواجهات والمقاطع)', 'المخططات الإنشائية', 'مخططات التأسيسات الميكانيكية والكهربائية', 'التنسيق بين الاختصاصات', 'جداول الكميات وتقدير الكلفة', 'التعديلات حتى الاعتماد'],
      faq: [['هل تقدمون كل المخططات في عقد واحد؟', 'نعم، المعماري والإنشائي والتأسيسات من فريق واحد مع تنسيق كامل.'], ['كيف أطلب التصميم؟', 'من صفحة «طلب تصميم» ارفع ما لديك من مخططات أو صور الأرض، ونرسل لك عرض السعر.']],
    },
    fa: {
      title: 'طراحی نقشه‌های معماری، سازه و تأسیسات | دفتر مهندسی فن آرا',
      h1: 'طراحی مهندسی: نقشه‌های معماری، سازه و تأسیسات',
      description: 'دفتر مهندسی چندرشته‌ای فن آرا: طراحی نقشه‌های معماری، سازه، تأسیسات مکانیکی و برقی برای ساختمان‌های مسکونی و تجاری، همراه با متره و برآورد.',
      intro: 'تیم فن آرا از مهندسان همه‌ی رشته‌ها تشکیل شده است؛ نقشه‌های هماهنگ معماری، سازه و تأسیسات را یک‌جا دریافت می‌کنید.',
      points: ['نقشه‌های معماری (پلان، نما، برش)', 'نقشه‌های سازه', 'نقشه‌های تأسیسات مکانیکی و برقی', 'هماهنگی بین رشته‌ها', 'متره، برآورد و تخمین هزینه', 'اصلاحات تا تأیید نهایی'],
      faq: [['همه‌ی نقشه‌ها را یک‌جا ارائه می‌دهید؟', 'بله؛ معماری، سازه و تأسیسات توسط یک تیم و با هماهنگی کامل.']],
    },
    en: {
      title: 'Architectural, Structural & MEP Design Office | Fanara Engineering',
      h1: 'Engineering Design: Architectural, Structural and MEP Drawings',
      description: 'A multidisciplinary engineering office producing architectural, structural, mechanical and electrical drawings for homes, apartment buildings and commercial projects in Iraq, with BOQs.',
      intro: 'The Fanara team covers every discipline, so you get coordinated architectural, structural and MEP drawings from one place — no clashes on site.',
      points: ['Architectural plans, elevations and sections', 'Structural drawings', 'Mechanical and electrical drawings', 'Inter-discipline coordination', 'BOQ and cost estimates', 'Revisions until approval'],
      faq: [['Do you deliver all drawings under one contract?', 'Yes — architecture, structure and MEP from one coordinated team.']],
    },
  },
]

export const serviceBySlug = (s: string) => SERVICE_PAGES.find((p) => p.slug === s)
