/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    projects: Project;
    team: Team;
    experience: Experience;
    credentials: Credential;
    highlights: Highlight;
    services: Service;
    'design-orders': DesignOrder;
    'order-files': OrderFile;
    feedback: Feedback;
    'highlight-comments': HighlightComment;
    media: Media;
    standards: Standard;
    'standard-files': StandardFile;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    team: TeamSelect<false> | TeamSelect<true>;
    experience: ExperienceSelect<false> | ExperienceSelect<true>;
    credentials: CredentialsSelect<false> | CredentialsSelect<true>;
    highlights: HighlightsSelect<false> | HighlightsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    'design-orders': DesignOrdersSelect<false> | DesignOrdersSelect<true>;
    'order-files': OrderFilesSelect<false> | OrderFilesSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    'highlight-comments': HighlightCommentsSelect<false> | HighlightCommentsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    standards: StandardsSelect<false> | StandardsSelect<true>;
    'standard-files': StandardFilesSelect<false> | StandardFilesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ('false' | 'none' | 'null') | false | null | ('fa' | 'ar' | 'en') | ('fa' | 'ar' | 'en')[];
  globals: {
    profile: Profile;
    'ai-settings': AiSetting;
  };
  globalsSelect: {
    profile: ProfileSelect<false> | ProfileSelect<true>;
    'ai-settings': AiSettingsSelect<false> | AiSettingsSelect<true>;
  };
  locale: 'fa' | 'ar' | 'en';
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  published?: boolean | null;
  featured?: boolean | null;
  order?: number | null;
  /**
   * فقط با اجازه‌ی کارفرما فعال شود
   */
  showClientName?: boolean | null;
  status: 'delivered' | 'in-progress';
  /**
   * اجرا = رزومه‌ی شخصی · طراحی = نمونه‌کار دفتر فن‌آرا
   */
  category: 'execution' | 'design';
  client?: string | null;
  location?: string | null;
  /**
   * مثلاً 2023 – 2025
   */
  period?: string | null;
  role?: string | null;
  summary?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  credits?:
    | {
        discipline: string;
        person: string;
        id?: string | null;
      }[]
    | null;
  systems?:
    | (
        | 'hvac'
        | 'plumbing'
        | 'drainage'
        | 'fire'
        | 'gas'
        | 'electrical-power'
        | 'lighting'
        | 'low-current'
        | 'plant-room'
        | 'finishing'
        | 'architecture'
        | 'infrastructure'
      )[]
    | null;
  cover?: (number | null) | Media;
  gallery?: (number | Media)[] | null;
  videos?: (number | Media)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  inGallery?: boolean | null;
  category?: ('site' | 'mep' | 'design' | 'team' | 'management') | null;
  sourceFile?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team".
 */
export interface Team {
  id: number;
  name: string;
  position: string;
  discipline: 'mechanical' | 'electrical' | 'design' | 'management';
  photo: number | Media;
  bio?: string | null;
  published?: boolean | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience".
 */
export interface Experience {
  id: number;
  title: string;
  company: string;
  location?: string | null;
  start: string;
  end?: string | null;
  current?: boolean | null;
  bullets?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  project?: (number | null) | Project;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials".
 */
export interface Credential {
  id: number;
  kind: 'degree' | 'certificate' | 'award';
  title: string;
  issuer?: string | null;
  year?: string | null;
  hours?: number | null;
  order?: number | null;
  verifyUrl?: string | null;
  /**
   * ⚠️ قبل از آپلود، کد ملی و اطلاعات شخصی را محو کنید. این تصویر عمومی است.
   */
  image?: (number | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "highlights".
 */
export interface Highlight {
  id: number;
  media: number | Media;
  caption?: string | null;
  album?: ('site' | 'design' | 'team' | 'academy') | null;
  link?: string | null;
  source?: ('manual' | 'instagram') | null;
  instagramId?: string | null;
  /**
   * فاز ۲: پس از اتصال حساب اینستاگرام فعال می‌شود
   */
  shareToInstagram?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: number;
  code: string;
  order?: number | null;
  title: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-orders".
 */
export interface DesignOrder {
  id: number;
  name: string;
  phone: string;
  email?: string | null;
  country?: string | null;
  city?: string | null;
  projectType: 'residential' | 'commercial' | 'industrial' | 'hotel' | 'petrochemical' | 'other';
  area?: number | null;
  floors?: number | null;
  services?: (number | Service)[] | null;
  files?: (number | OrderFile)[] | null;
  deadline?: string | null;
  notes?: string | null;
  status?: ('new' | 'review' | 'quoted' | 'in-design' | 'delivered' | 'closed') | null;
  quoteAmount?: string | null;
  internalNotes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-files".
 */
export interface OrderFile {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Comments visitors left in the exit feedback box.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: number;
  message: string;
  locale?: string | null;
  page?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "highlight-comments".
 */
export interface HighlightComment {
  id: number;
  highlight: number | Highlight;
  name: string;
  message: string;
  hidden?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "standards".
 */
export interface Standard {
  id: number;
  title: string;
  publisher?: string | null;
  number?: string | null;
  edition?: string | null;
  year?: string | null;
  discipline: 'mechanical' | 'electrical' | 'fire' | 'architecture' | 'civil' | 'structural' | 'energy' | 'general';
  country?: ('IR' | 'IQ' | 'US' | 'UK' | 'EU' | 'INT') | null;
  status: 'valid' | 'superseded' | 'verify';
  /**
   * عمومی‌پذیر = دستیار عمومی می‌تواند به آن ارجاع دهد. پیش‌فرض: خصوصی
   */
  accessTier: 'public' | 'private';
  file?: (number | null) | StandardFile;
  /**
   * فاز ۳
   */
  indexed?: boolean | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "standard-files".
 */
export interface StandardFile {
  id: number;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  role: 'admin' | 'editor' | 'orders' | 'instructor' | 'customer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'team';
        value: number | Team;
      } | null)
    | ({
        relationTo: 'experience';
        value: number | Experience;
      } | null)
    | ({
        relationTo: 'credentials';
        value: number | Credential;
      } | null)
    | ({
        relationTo: 'highlights';
        value: number | Highlight;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'design-orders';
        value: number | DesignOrder;
      } | null)
    | ({
        relationTo: 'order-files';
        value: number | OrderFile;
      } | null)
    | ({
        relationTo: 'feedback';
        value: number | Feedback;
      } | null)
    | ({
        relationTo: 'highlight-comments';
        value: number | HighlightComment;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'standards';
        value: number | Standard;
      } | null)
    | ({
        relationTo: 'standard-files';
        value: number | StandardFile;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  published?: T;
  featured?: T;
  order?: T;
  showClientName?: T;
  status?: T;
  category?: T;
  client?: T;
  location?: T;
  period?: T;
  role?: T;
  summary?: T;
  body?: T;
  credits?:
    | T
    | {
        discipline?: T;
        person?: T;
        id?: T;
      };
  systems?: T;
  cover?: T;
  gallery?: T;
  videos?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team_select".
 */
export interface TeamSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  discipline?: T;
  photo?: T;
  bio?: T;
  published?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "experience_select".
 */
export interface ExperienceSelect<T extends boolean = true> {
  title?: T;
  company?: T;
  location?: T;
  start?: T;
  end?: T;
  current?: T;
  bullets?:
    | T
    | {
        text?: T;
        id?: T;
      };
  project?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "credentials_select".
 */
export interface CredentialsSelect<T extends boolean = true> {
  kind?: T;
  title?: T;
  issuer?: T;
  year?: T;
  hours?: T;
  order?: T;
  verifyUrl?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "highlights_select".
 */
export interface HighlightsSelect<T extends boolean = true> {
  media?: T;
  caption?: T;
  album?: T;
  link?: T;
  source?: T;
  instagramId?: T;
  shareToInstagram?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  code?: T;
  order?: T;
  title?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "design-orders_select".
 */
export interface DesignOrdersSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  email?: T;
  country?: T;
  city?: T;
  projectType?: T;
  area?: T;
  floors?: T;
  services?: T;
  files?: T;
  deadline?: T;
  notes?: T;
  status?: T;
  quoteAmount?: T;
  internalNotes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "order-files_select".
 */
export interface OrderFilesSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  message?: T;
  locale?: T;
  page?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "highlight-comments_select".
 */
export interface HighlightCommentsSelect<T extends boolean = true> {
  highlight?: T;
  name?: T;
  message?: T;
  hidden?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  inGallery?: T;
  category?: T;
  sourceFile?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "standards_select".
 */
export interface StandardsSelect<T extends boolean = true> {
  title?: T;
  publisher?: T;
  number?: T;
  edition?: T;
  year?: T;
  discipline?: T;
  country?: T;
  status?: T;
  accessTier?: T;
  file?: T;
  indexed?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "standard-files_select".
 */
export interface StandardFilesSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile".
 */
export interface Profile {
  id: number;
  heroEyebrow?: string | null;
  heroTitle: string;
  heroText?: string | null;
  heroImage?: (number | null) | Media;
  name: string;
  role?: string | null;
  summary?: string | null;
  portrait?: (number | null) | Media;
  cvPdf?: (number | null) | Media;
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  languages?:
    | {
        language: string;
        level?: string | null;
        id?: string | null;
      }[]
    | null;
  skills?:
    | {
        group: string;
        /**
         * هر مورد در یک خط
         */
        items?: string | null;
        id?: string | null;
      }[]
    | null;
  whatsapp?: string | null;
  phoneIraq?: string | null;
  email?: string | null;
  instagramOffice?: string | null;
  instagramPersonal?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings".
 */
export interface AiSetting {
  id: number;
  enabled?: boolean | null;
  /**
   * از console.anthropic.com → API Keys بسازید و اینجا بچسبانید. فقط مدیر کل آن را می‌بیند.
   */
  apiKey?: string | null;
  model?: ('claude-haiku-4-5' | 'claude-sonnet-5-5') | null;
  perVisitorDaily?: number | null;
  totalDaily?: number | null;
  /**
   * مثلاً تخفیف ویژه، ساعات پاسخ‌گویی، یا نکته‌ای که دستیار باید بداند.
   */
  extraInstructions?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "profile_select".
 */
export interface ProfileSelect<T extends boolean = true> {
  heroEyebrow?: T;
  heroTitle?: T;
  heroText?: T;
  heroImage?: T;
  name?: T;
  role?: T;
  summary?: T;
  portrait?: T;
  cvPdf?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  languages?:
    | T
    | {
        language?: T;
        level?: T;
        id?: T;
      };
  skills?:
    | T
    | {
        group?: T;
        items?: T;
        id?: T;
      };
  whatsapp?: T;
  phoneIraq?: T;
  email?: T;
  instagramOffice?: T;
  instagramPersonal?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ai-settings_select".
 */
export interface AiSettingsSelect<T extends boolean = true> {
  enabled?: T;
  apiKey?: T;
  model?: T;
  perVisitorDaily?: T;
  totalDaily?: T;
  extraInstructions?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}